### ISSUE TITLE
404 Not found relationships when create / edit

### ISSUE THREAD

**Issue by dillingham** [eminiarts/nova-relationship-selector#2]
Nova: 1.2.1
Laravel 5.7

### Description

Seems when you use this package it prevents the registration of the field in other aspects like creating from relation or editing viaRelationship. If you click create or edit a row, the console says 404

![bug](https://user-images.githubusercontent.com/29180903/50483589-73a0dd00-09ba-11e9-8713-89b2ac5b1152.png)

Also seems like the endpoint its requesting might be wrong

**Comment by bajramemini** [comment]
Hello @dillingham 

I had the same issue with eminiarts/nova-tabs#1 before, that's why I knew what it was.

Going to tag it in a bit.

Let me know if there is anything else.

Regards
Bajram

**Comment by dillingham** [comment]
@bajramemini 

Ah! Glad it was a easy fix :)

I found a few other things. I will continue to look for edge cases.

- Brian
