### ISSUE TITLE
Other form-selects get cut off

### ISSUE THREAD

**Issue by dillingham** [eminiarts/nova-relationship-selector#7]
nova 1.2.1
laravel 5.7
package 0.1.0

### Description
PR https://github.com/eminiarts/nova-relationship-selector/pull/3 .form-select text-indent effects other selects in filters & actions. 
Need to add a class to the "header select" and add that text indent -5 to it instead
![whoops](https://user-images.githubusercontent.com/29180903/50495281-2d696f00-09f6-11e9-81c0-82eb28208301.png)

**Comment by bajramemini** [comment]
Hello @dillingham. 

Thanks for the issues. Going to work on them tomorrow.
