### ISSUE TITLE
Support for BelongsTo Relationship

### ISSUE THREAD

**Issue by dillingham** [eminiarts/nova-relationship-selector#8]
nova 1.2.1
laravel 5.7
release: 0.1.1
type: request

### Description

In some cases it may be valuable to display a BelongsTo relationship in the dropdown.
"vendor" of an "invoice" and "items" of an "invoice" could both options in the dropdown.
I imagine when selecting, you would be presented with the detail panel vs a table.

### Usage
 
```php
// App\Nova\Invoice
```
```php
RelationshipSelector::make('Relations')
    ->addOption('Vendor', BelongsTo::make('Vendor'),
    ->addOption('Items', HasMany::make('Items'),
```
![vendor](https://user-images.githubusercontent.com/29180903/50540196-6bcc6e80-0b5b-11e9-8af0-f8bf0a47869c.PNG)

Sidenote: changing the fields for this specific display would be as simple as creating a new resource 

```php
RelationshipSelector::make('Relations')
    ->addOption('Vendor', BelongsTo::make('Vendor'), // default
    ->addOption('Vendor', BelongsTo::make('Vendor', 'vendor', 'App\Nova\OrderVendor'), // custom
```

**Comment by bajramemini** [comment]
Hello @dillingham 

Sorry for the long delay. Got a few days off and had a lot to do afterwards.

I did not manage to resolve the issue completely yet.

```vue
<component
  v-if="tab.field.component == 'belongs-to-field'"
  :is="'panel'"
  :resource-name="resourceName"
  :resource-id="resourceId"
  :resource="resource"
  :panel="{
    showToolbar: false,
    component:'panel',
    fields: [tab.field],
    name: tab.field.panel,
  }"
  @actionExecuted="actionExecuted"
/>
<component
  v-else
  :is="'detail-' + tab.field.component"
  :resource-name="resourceName"
  :resource-id="resourceId"
  :resource="resource"
  :field="tab.field"
  @actionExecuted="actionExecuted"
/>
```

which gives me:
![image](https://user-images.githubusercontent.com/3426944/50725226-bcfbd580-10fa-11e9-9684-b4b084bb6321.png)

After having a look at the fields-api, I see that the value is not retrieved correctly:

![image](https://user-images.githubusercontent.com/3426944/50725232-d7ce4a00-10fa-11e9-8087-ca20d5f1077b.png)

So **value** and **belongsToId** are missing. I could try to fetch them in `RelationshipiSelector.php` but it feels a bit hacky.

I would use a belongs-to-field in the default Panel but I get that it could be used in the Relationship-Selector.

But you would only have a Panel with one Field in it, is that correct/the intended behaviour?

Regards

**Comment by dillingham** [comment]
Hi @bajramemini,

Yeah I suppose this is a bit of an edge case where it isn't treated as a field.
I think the Detail.vue panel & it's dependencies should be rendered uniquely instead if belongsto.
The intended behavior / suggestion is to offer the display the entire Detail.vue panel vs just the link.
I'm not sure showing just a row with a link is of much value or would feel as natural.

In the screenshot, the selector has items (Table) and vendor (Detail) that relate to the order.

**Comment by bajramemini** [comment]
Just fyi:

Nova resolves all fields during the request. So I had to resolve all Options to retrieve the correct values.

```php
/**
 * Resolve the fields in the Options
 * @return mixed
 */
public function resolve($resource, $attribute = null)
{
    return collect($this->options)->each(function ($option, $key) use ($resource) {
        if ($option['field'] instanceof Resolvable) {
            $option['field']->resolve($resource);
        };
    });
}
```

Will tag it shortly.

Regards
