### ISSUE TITLE
[Feature Request] Add "Per Page" Filter

### ISSUE THREAD

**Issue by chescos** [eminiarts/nova-relationship-selector#9]
I'm not sure whether this is possible but it would be awesome to have the default "Per Page" filter on the relationship selector so that it isn't limited to just 5 rows per page.

**Comment by dillingham** [comment]
If you want to change that setting, you have to do so in the way Nova provides currently. 

Adding the following to your resources, or base resource, will override the per page. 

```php
public static $perPageViaRelationship = 5;
```

Nova does not currently support Per Page filter drop downs on relationships.

**Comment by bajramemini** [comment]
Thank you @dillingham for the help!

**Comment by bajramemini** [comment]
@chescos since this has nothing to do with the package itself, I am going to close this issue. 

If this functionality changes in Nova, I am happy to reopen the issue and work on it.
